---
language: python
sudo: required
cache:
  pip: true

env:
  global:
    - fast_finish: true

services:
  - docker

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get -y install python-pip libssl-dev
  - pip install --upgrade setuptools
  - pip install molecule
  - pip install molecule[docker]
  - WDIR=$(pwd)
  - cd /opt
  - curl -L https://networkgenomics.com/try/mitogen-0.2.9.tar.gz | tar -xz
  - cd $WDIR

script:
  - molecule test --all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    on_failure: change
    on_success: never
