---
language: python
sudo: required
cache:
  pip: true

env:
  global:
    - fast_finish: true
    - GCE_CREDENTIALS_FILE=$TRAVIS_BUILD_DIR/refined-bolt-255914-bd6db447e6eb.json
    - GCE_PROJECT_ID=refined-bolt-255914

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - curl https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-281.0.0-linux-x86_64.tar.gz | tar -xz -C /tmp
  - /tmp/google-cloud-sdk/install.sh --quiet
  - openssl aes-256-cbc -K $encrypted_5a0f64e3888d_key -iv $encrypted_5a0f64e3888d_iv -in refined-bolt-255914-bd6db447e6eb.json.enc -out refined-bolt-255914-bd6db447e6eb.json -d
  - gcloud auth activate-service-account --key-file $GCE_CREDENTIALS_FILE
  - gcloud config set project $GCE_PROJECT_ID

install:
  - sudo apt-get -y install python-pip libssl-dev git
  - git clone https://github.com/kewlfft/ansible-aur.git ~/.ansible/plugins/modules/aur
  - pip install --upgrade setuptools
  - pip install ansible-lint
  - pip install flake8
  - pip install testinfra
  - pip install molecule
  - pip install molecule-gce
  - WDIR=$(pwd)
  - cd /opt
  - curl -L https://networkgenomics.com/try/mitogen-0.2.9.tar.gz | tar -xz
  - cd $WDIR

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    on_failure: change
    on_success: never
