---
- name: User .local pathmunge
  become: true
  copy:
    content: |
      #!/bin/sh
      export PATH=$HOME/.local/bin:$PATH
    dest: /etc/profile.d/userpath.sh
    mode: 0755

- name: Creating user config directory
  become: true
  become_user: "{{ item.key }}"
  file:
    path: "{{ item.value['home'] }}/.config/tmux/"
    mode: 0700
    owner: "{{ item.key }}"
    state: directory
  loop: "{{ lookup('dict', xrdp_user_list, wantlist=true) }}"
  when: xrdp_user_config|bool

- name: Installing user config
  become: true
  copy:
    src: files/.tmux.conf
    dest: "{{ item.value['home'] }}/.tmux.conf"
    owner: "{{ item.key }}"
    mode: 0600
    attr: +i
  loop: "{{ lookup('dict', xrdp_user_list, wantlist=true) }}"
  when: xrdp_user_config|bool
