---
- name: Installing xrdp (Package, not arch)
  become: true
  package:
    name: xrdp
  when: 
    - xrdp.package
    - ansible_os_family != "Archlinux"

- name: Installing xrdp (Package, arch)
  become: true
  become_user: "{{ aur_user }}"
  aur:
    name: xrdp
    skip_installed: true
  when:
    - xrdp.package
    - (xrdp.package) != (xrdp.source is defined)
    - ansible_os_family == "Archlinux"

- name: Installing xrdp (Source)
  include_role:
    name: jonsible.builder
    tasks_from: builder.yml
  vars:
    prefix: "{{ item.prefix }}"
    version: "{{ item.version }}"
    owner: "{{ item.owner }}"
  loop: "{{ xrdp.source.contexts }}"
  when: xrdp.source is defined

- name: Starting and enabling services
  become: true
  systemd:
    name: "{{ item }}"
    enabled: true
    daemon_reload: true
    state: started
  loop:
    - xrdp
    - xrdp-sesman
  when: ansible_service_mgr == "systemd"

- name: Starting and enabling services
  become: true
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - xrdp
    - xrdp-sesman
  when: ansible_service_mgr != "systemd"
