---
- name: Installing xrdp
  become: true
  package:
    name: xrdp
    state: present
    update_cache: true
  when: ansible_os_family != "Archlinux"

- name: Installing xrdp (Arch)
  become: true
  become_user: aur_builder
  aur:
    name: xrdp
    use: yay
    skip_installed: true
  when: ansible_distribution == "Archlinux"
