---
- name: Exiting if no user filter/strip provided
  assert:
    that: >
      xrdp_user_strip|length > 0 or
      xrdp_user_filter|length > 0

- name: Getting ulist
  include_role:
    name: jonsible.ulist
    tasks_from: set_ulist.yml
  when: xrdp_user_list|length == 0

- name: Setting ulist if xrdp_user_list is set
  set_fact:
    ulist: "{{ xrdp_user_list }}"
  when: xrdp_user_list|length != 0

- name: Processing ulist
  include_role:
    name: jonsible.ulist
    tasks_from: process_ulist.yml
  vars:
    filter: "{{ xrdp_user_filter }}"
    strip: "{{ xrdp_user_strip }}"

- name: Setting user_list
  set_fact:
    xrdp_user_list: "{{ ulist }}"
