---
- include_tasks: source/prepare.yml

- include_tasks: source/uninstall.yml
  when:
    - xrdp_installed.stat.exists
    - >
      (xrdp_git_version != xrdp_local_version) or
      xrdp_force_install|bool

- include_tasks: source/install.yml
  when: >
    not xrdp_installed.stat.exists or
    xrdp_force_install|bool or
    (xrdp_git_version != xrdp_local_version)
