---
- name: Update cache (EL)
  become: true
  yum:
    update_cache: true
  tags: molecule-idempotence-notest

- name: Installing build tools
  become: true
  yum:
    name: "{{ build_tools }}"
    state: present
  when: xrdp_install_from_source|bool

- name: Installing additionnal dependencies
  become: true
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - finger
    - cmake
    - patch
    - gcc
    - make
    - autoconf
    - libtool
    - automake
    - pkgconfig
    - openssl-devel
    - gettext
    - file
    - pam-devel
    - libX11-devel
    - libXfixes-devel
    - libjpeg-devel
    - flex
    - bison
    - gcc-c++
    - libxslt
    - perl-libxml-perl
    - xorg-x11-font-utils
    - xmlto-tex
    - libXrandr-devel
    - nasm
    - xorg-x11-server-devel
    - xorg-x11-server-Xorg
    - xorg-x11-xinit
    - libXfont2
    - libXfont2-devel
  when: xrdp_install_from_source|bool

- name: Installing firewalld
  become: true
  yum:
    name: firewalld
    state: present

- name: Start/Enable firewalld
  become: true
  service:
    name: firewalld
    enabled: true
    state: started

- name: Allowing 3389/tcp
  become: yes
  firewalld:
    port: 3389/tcp
    permanent: yes
    state: enabled
  notify: firewalld_reload

- name: Allowing 3389/udp
  become: yes
  firewalld:
    port: 3389/udp
    permanent: yes
    state: enabled
  notify: firewalld_reload