---
dependency:
  name: galaxy
driver:
  name: gce
lint: |
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: gcp-ubuntu-1804
    zone: europe-west3-a
    machine_type: f1-micro
    image_family: ubuntu-1804-lts
    image_project: ubuntu-os-cloud
  - name: gcp-arch-latest
    zone: europe-west3-a
    machine_type: f1-micro
    image_family: arch
    image_project: arch-linux-gce
provisioner:
  name: ansible
  env:
    # yamllint disable-line rule:line-length
    ANSIBLE_STRATEGY_PLUGINS: /opt/mitogen-0.2.9/ansible_mitogen/plugins/strategy
    ANSIBLE_STRATEGY: mitogen_linear
    ANSIBLE_PIPELINING: true
verifier:
  name: ansible
