---
dependency:
  name: galaxy
driver:
  name: gce
platforms:
  - name: gcp-gce-ubuntu
    zone: europe-west3-a
    machine_type: f1-micro
    image: ubuntu-1804-bionic-v20190617 
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
