---
- name: Creating xrdp versioned directory
  become: true
  file:
    path: "{{ source_path }}/xrdp-{{ xrdp_git_version }}/"
    state: directory
    mode: 0755

- name: Downloading the latest version of xrdp
  become: true
  unarchive:
    src: "{{ xrdp_source_url }}"
    dest: "{{ source_path }}/xrdp-{{ xrdp_git_version }}/"
    extra_opts:
      - --strip-components=1
    remote_src: true

- name: Configuring xrdp
  become: true
  shell: |
    ./boostrap
    ./configure --prefix="{{ prefix }}" \
    --with-systemdsystemunitdir=/usr/lib/systemd/system \
    --enable-jpeg \
    --enable-tjpeg \
    --enable-fuse \
    --enable-opus \
    --enable-rfxcodec \
    --enable-mp3lame \
    --enable-pixman \
    --enable-painter \
    --enable-vsock \
  changed_when: false
  args:
    chdir: "{{ source_path }}/xrdp-{{ xrdp_git_version }}/"

- name: Making xrdp
  become: true
  make:
    chdir: "{{ source_path }}/xrdp-{{ xrdp_git_version }}"

- name: Installing xrdp
  become: true
  changed_when: false
  make:
    chdir: "{{ source_path }}/xrdp-{{ xrdp_git_version }}"
    target: install
    params:
      PREFIX: "{{ prefix }}"
